### PR TITLE
Boot run

### PR DESCRIPTION
**Pull request by mpwaller**
I moved a lot of things around - mainly due to naming.

I simplified the README page.

Now ./gradlew yoink is an alias for ./graldew bootRun

### CODE REVIEW

**Comment by zhengmin317** [comment]
under branch bootRun:
./graldew bootRun throws error.

screen shot 2016-06-20 at 09 26 12

**Comment by zhengmin317** [comment]
git branch

git pull

./gradlew bootRun

Error:
screen shot 2016-06-20 at 12 23 09

**Comment by mpwaller** [comment]
ok, thanks for that. I have fixed a lot of the code. 

One problem is that Unit tests passed, but the spring wiring was not working. 

So 

`./gradlew clean build` 

was not throwing an error.  In other words, we have no real integration tests that check the spring wiring.

**Comment by zhengmin317** [comment]
The integration-test was under yoink-core-bootstrap.

I added integration-test in  ./yoink/build.gradle. However there is 
error  calling Application.main() in integration-test.

I do not have a clue why.

**Pull request closed without merging**
